// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufbxinggoxjxtytksnrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmYnhpbmdnb3hqeHR5dGtzbnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTc0MjcsImV4cCI6MjA2OTc5MzQyN30.n1uB3zKHCW-E6zIDHs46b7Av6o8u124k-kZ4Srda95E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});